config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/markwilkinson/FAIR-Champion:
      branch: master
      repo: https://github.com/markwilkinson/FAIR-Champion.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/markwilkinson/FAIR-Champion git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-taupe-dogfish.sh
        container: qc.acc_goopy-gamboge-emu
  QC.Doc:
    repos:
      github.com/markwilkinson/FAIR-Champion find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-harlequin-tamarin.sh
        container: qc.doc_crappy-rose-bandicoot
      github.com/markwilkinson/FAIR-Champion git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-corn-angelfish.sh
        container: qc.doc_shaggy-rose-cow
      github.com/markwilkinson/FAIR-Champion markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-blue-eleuth.sh
        container: qc.doc_zippy-tomato-tzu
  QC.Lic:
    repos:
      github.com/markwilkinson/FAIR-Champion licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-tomato-tamarin.sh
        container: qc.lic_snoopy-cerulean-zorse
  QC.Sty:
    repos:
      github.com/markwilkinson/FAIR-Champion hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-lime-goat.sh
        container: qc.sty_muzzy-bistre-sloth
      github.com/markwilkinson/FAIR-Champion jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-ivory-heron.sh
        container: qc.sty_lanky-vermilion-jackal
      github.com/markwilkinson/FAIR-Champion rubocop:
        commands:
        - /usr/bin/env sh .sqa/script.ready-gold-olm.sh
        container: qc.sty_randy-saffron-grasshopper
  QC.Ver:
    repos:
      github.com/markwilkinson/FAIR-Champion get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-lemon-snail.sh
        container: qc.ver_chummy-fuchsia-hound
timeout: 5400
